### ISSUE TITLE
Login and logout users

### ISSUE THREAD

**Issue by oguntli** [angryshortone/GrumpONado#10]
## Detailed Description

Users should be able to login and logout

## Possible Implementation

JWT seems a sound idea, as it also would allow to be reused on websockets

## Tasks
- [X] Post route for login
- [x] Delete route for logout
- [x] Compare password hashes
- [x] Return a authenticated header with jwt
- [x] Validate jwt and authentication on consecutive requests
- [x] Invalidate token on logout
